spring:
  datasource:
    url: ${DATA_URL:jdbc:sqlserver://mssql-190917-0.cloudclusters.net:18969;databaseName=delbank;encrypt=true;trustServerCertificate=true}
    username: ${DATA_USER:admin}
    password: ${DATA_PASSWORD:Amadeukkk123@}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect

  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq-190915-0.cloudclusters.net}
    port: ${RABBIT_PORT:10050}
    username: ${RABBIT_USERNAME:admin}
    password: ${RABBIT_PASSWORD:agkCAYWt}

  logging:
    level:
      root: INFO
      org.springframework: DEBUG
      com.deltech: TRACE
      org.hibernate.SQL: DEBUG
    file:
      name: logs/application.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

  management:
    endpoints:
      web:
        exposure:
          include: loggers
    endpoint:
      loggers:
        enabled: true