spring:
  datasource:
    url: ${DATA_URL:jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true}
    username: ${DATA_USER:sa}
    password: ${DATA_PASSWORD:admin123!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:admin123!}
    password: ${RABBIT_PASSWORD:admin123!}

  logging:
    level:
      root: INFO
      org.springframework: DEBUG
      com.deltech: TRACE
      org.hibernate.SQL: DEBUG
    file:
      name: logs/application.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

  management:
    endpoints:
      web:
        exposure:
          include: loggers
    endpoint:
      loggers:
        enabled: true